services:
    _defaults:
        autowire: true
        autoconfigure: true

    Wow\Ext\Containers\:
        resource: '../src/'
        exclude:
            - '../src/Contracts/'
            - '../src/Domain/Enum/'

    Wow\Ext\Containers\Contracts\ContainerServiceInterface:
        alias: Wow\Ext\Containers\Application\Service\ContainerService

    Wow\Ext\Containers\Contracts\StackServiceInterface:
        alias: Wow\Ext\Containers\Application\Service\StackService
